config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  get 'posts/index'
  get 'posts/new'
  post 'posts/create'
  get 'posts/show/:id' => "posts#show"
  get 'posts/edit/:id' => "posts#edit"
  post 'posts/update/:id' => "posts#update"
  get 'posts/destroy/:id' => "posts#destroy"
  
  post "posts/:post_id/comments/create" => "comments#create"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # skip_before_action :verify_authenticity_token
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # 특정 글의 댓글을 저장한다
    # Comment.create(user_name: params[:user_name], body: params[:body], post_id: params[:post_id])
    
    # 1.특정 글을 가져온다.
    post = Post.find(params[:post_id])
    # 2. 특정 글의 댓글을 저장한다.
    post.comments.create(body: params[:body], user_id: current_user.id)
    
    
    # 요청했던 전 페이지로 이동한다.
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  
  def new
  end

  def create
    @post = Post.new
    
    @post.title = params[:title]
    @post.content = params[:content]
    @post.user_id = current_user.id
    
    @post.save
    
    redirect_to "/posts/show/#{@post.id}"
  end

  def index
    @posts = Post.all
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    post = Post.find(params[:id])
    
    post.title = params[:title]
    post.content = params[:content]
    
    post.save
    
    redirect_to "/posts/show/#{post.id}"
  end
  
  def destroy
    @post = Post.find(params[:id])
    
    @post.destroy
    
    redirect_to "/posts/index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudExamApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= any_login_here if defined?(AnyLogin) %>
  </body>
</html>

app/views/posts/edit.html.erb
<h3><%= @post.id %>번 글 수정</h3>

<form action="/posts/update/<%= @post.id %>" method="POST">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <label for="post_title">제목</label>
    <input type="text" name="title" value="<%= @post.title %>" id="post_title">
    <br>
    <label for="post_content">제목</label>
    <textarea name="content" id="post_content"><%= @post.content %></textarea>
    <button type="submit">제출</button>
</form>

app/views/posts/index.html.erb
<% if user_signed_in? %>
    <%= current_user.email %> 님 안녕하세요.
    <a href="/users/sign_out" data-method="delete">로그아웃</a>
<% else %>
    <a href="/users/sign_in">로그인</a>
<% end %>
<hr>

<% @posts.each do |post| %>
    title : <%= post.title %>
    content : <%= post.content %>
    <a href="/posts/show/<%= post.id %>">보기</a>
    <a href="/posts/edit/<%= post.id %>">수정</a>
    <a href="/posts/destroy/<%= post.id %>">삭제</a>
    <hr>
<% end %>

<a href="<%= posts_new_path %>">글 작성하러 가기</a>

app/views/posts/new.html.erb
<h3>새 글 작성</h3>

<form action="/posts/create" method="POST">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <label for="post_title">제목</label>
    <input type="text" name="title" id="post_title">
    <br>
    <label for="post_content">내용</label>
    <textarea name="content" id="post_content"></textarea>
    <button type="submit">제출</button>
</form>

app/views/posts/show.html.erb
<%= @post.id %> 의 글
<hr>
title : <%= @post.title %>
<hr>
content : <%= @post.content %>
<hr>
email : <%= @post.user.email %>
<hr>
작성자의 댓글 작성 수 : <%= @post.user.comments.count %>
<hr>

<h3>댓글 작성</h3>

<form action="/posts/<%= @post.id %>/comments/create" method="POST">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    내용 : <input type="text" name="body">
    <button>제출</button>
</form>

<hr>

<h3>댓글 리스트</h3>
<!-- 특정 글의 댓글들을 보여준다.-->
<% @post.comments.each do |comment| %>
    작성자 : <%= comment.user.email %>
    내용 : <%= comment.body %>
    <hr>
<% end %>


<a href="/posts/index">리스트로 이동</a>